fn main() {
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "open_document_window",
            "close_document_window",
            "focus_library_window",
            "data_query",
            "data_mutate",
            "blob_import",
            "blob_read",
            "blob_ensure",
            "local_clear_data",
            "blob_discard",
            "local_setting_get",
            "local_setting_set",
            "local_account_set",
            "local_account_remove",
            "local_recovery_export",
            "sync_now",
            "opened_file_read",
            "opened_file_open",
            "request_sign_in",
            "local_annotations_list",
            "local_annotation_put",
            "local_annotation_delete",
            "local_annotations_clear",
            "pdf_viewer_status",
            "pdf_viewer_make_default",
        ]),
    ))
    .expect("failed to prepare the Papol desktop build")
}
