[package]
name = "papol-desktop"
version = "0.1.0"
description = "The Papol desktop application"
authors = ["Papol contributors"]
edition = "2021"

[lib]
name = "papol_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
