[package]
name = "papol-desktop"
version = "0.1.0"
description = "The Papol desktop application"
authors = ["Papol contributors"]
edition = "2021"

[lib]
name = "papol_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-http = "2"

# Included in Tauri 2.12. Remove this patch after upgrading.
[patch.crates-io]
tao = { git = "https://github.com/tauri-apps/tao", rev = "7d2cdb1aedb992e6b70d104b392809847944edd6" }
