import test from 'node:test';
import assert from 'node:assert/strict';
import { readdir, readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const tauriRoot = path.join(repositoryRoot, 'desktop', 'src-tauri');
const sorted = (values) => [...new Set(values)].sort();

function names(source, pattern) {
  return [...source.matchAll(pattern)].map((match) => match[1]);
}

test('every native command is registered, permitted, and granted to a window', async () => {
  const [rust, build, mainCapability, documentCapability, permissionFiles] = await Promise.all([
    readFile(path.join(tauriRoot, 'src', 'lib.rs'), 'utf8'),
    readFile(path.join(tauriRoot, 'build.rs'), 'utf8'),
    readFile(path.join(tauriRoot, 'capabilities', 'main.json'), 'utf8').then(JSON.parse),
    readFile(path.join(tauriRoot, 'capabilities', 'documents.json'), 'utf8').then(JSON.parse),
    readdir(path.join(tauriRoot, 'permissions', 'autogenerated')),
  ]);

  const commands = sorted(names(
    rust,
    /#\[tauri::command\]\s*(?:async\s+)?fn\s+([a-z_]+)/g,
  ));
  const handlerBody = rust.match(/generate_handler!\[([\s\S]*?)\]/)?.[1] || '';
  const registered = sorted(names(handlerBody, /\b([a-z_]+)\s*,?/g));
  const manifestBody = build.match(/commands\(&\[([\s\S]*?)\]\)/)?.[1] || '';
  const manifested = sorted(names(manifestBody, /"([a-z_]+)"/g));
  const permitted = sorted(permissionFiles
    .filter((file) => file.endsWith('.toml'))
    .map((file) => file.slice(0, -'.toml'.length)));
  const granted = sorted([...mainCapability.permissions, ...documentCapability.permissions]
    .filter((permission) => typeof permission === 'string' && permission.startsWith('allow-'))
    .map((permission) => permission.slice('allow-'.length).replaceAll('-', '_')));

  assert.deepEqual(registered, commands, 'runtime handler and #[tauri::command] functions differ');
  assert.deepEqual(manifested, commands, 'build-time command manifest is incomplete');
  assert.deepEqual(permitted, commands, 'generated native command permissions differ');
  assert.deepEqual(granted, commands, 'some native commands are not granted to any window');
});
